version: '3.8'

services:
  db:
    image: postgres:16.4-alpine
    container_name: stories
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stories_db
    volumes:
      - stories_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stories_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stories_network

networks:
  stories_network:
    driver: bridge

volumes:
  stories_pgdata:
    driver: local
